title: Minimal theme
logo: /assets/img/sa.png
description: Solution Architect & Performance specialist with over 15 plus year experience in Oracle Database/ Unix/Linux/Windows and Virtualization (VMware/KVM/HyperV)/Docker and kubernetes.Vast knowledge cross plarform Oracle database migrations / solutioning / Exadata compete offerings /Storage administration/ Performance Benchmarking / Proof of Concept. Very good knoledge in automation using ansible/shell scripts and currently working as Solution Architect at HPE and working with Global customers around Database Modenization/TCO Optimization/Performance Benchmarking/Datacenter Modenization.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
